# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scrapping.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from untitled import *
from about import *
from PyQt5 import QtCore, QtGui, QtWidgets
import csv


class Ui_window2(object):
    def setupUi(self, window2):
        window2.setObjectName("window2")
        window2.resize(886, 574)
        window2.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(window2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 131, 551))
        self.label.setStyleSheet("background-color: rgb(85, 0, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 470, 51, 51))
        self.pushButton_3.setStyleSheet("background-image: url(:/newPrefix/C:/Users/DEll/OneDrive/Pictures/Screenshots/login.png);\n"
"background-image: url(:/newPrefix/pic/login.png);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(130, 0, 731, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 130, 711, 321))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 450, 711, 61))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 0, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 50, 51, 23))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 20, 51, 23))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(100, 30, 161, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(90, 30, 111, 31))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 35, 71, 21))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton.setGeometry(QtCore.QRect(380, 30, 121, 21))
        self.radioButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_2.setGeometry(QtCore.QRect(380, 50, 121, 21))
        self.radioButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 470, 721, 41))
        self.pushButton_7.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(-5, 130, 721, 341))
        self.tableWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 130, 721, 341))
        self.tableWidget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(7)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 61, 21))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit.setGeometry(QtCore.QRect(100, 20, 261, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_2.setGeometry(QtCore.QRect(420, 20, 201, 22))
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 470, 721, 41))
        self.pushButton_8.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab_3, "")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 50, 111, 51))
        self.pushButton.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 120, 111, 51))
        self.pushButton_2.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        window2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 886, 21))
        self.menubar.setObjectName("menubar")
        window2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window2)
        self.statusbar.setObjectName("statusbar")
        window2.setStatusBar(self.statusbar)

        self.retranslateUi(window2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(window2)
        
        #*********************************************************
        self.pushButton.clicked.connect(self.loadHomeWindow)
        self.pushButton.clicked.connect(window2.close)
        self.pushButton_2.clicked.connect(self.loadAboutWindow)
        self.pushButton.clicked.connect(window2.close)
        self.pushButton_3.clicked.connect(self.loadHomeWindow)
        self.pushButton.clicked.connect(window2.close)
    def loadHomeWindow(self):
        self.Home = QtWidgets.QMainWindow()
        self.ui = Ui_Home()
        self.ui.setupUi(self.Home)
        self.Home.show()
    def loadAboutWindow(self):
        self.window3 = QtWidgets.QMainWindow()
        self.ui = Ui_window3()
        self.ui.setupUi(self.window3)
        self.window3.show()

    def retranslateUi(self, window2):
        _translate = QtCore.QCoreApplication.translate
        window2.setWindowTitle(_translate("window2", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("window2", "University"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("window2", "Course Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("window2", "Lecture Videos"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("window2", "Duration"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("window2", "Students Enrolled"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("window2", "Professor"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("window2", "Price"))
        self.pushButton_4.setText(_translate("window2", "Load Data From csv"))
        self.pushButton_5.setText(_translate("window2", "Pause"))
        self.pushButton_6.setText(_translate("window2", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("window2", "Scrapping"))
        self.comboBox.setItemText(0, _translate("window2", "Insertion Sort"))
        self.comboBox.setItemText(1, _translate("window2", "Merge Sort"))
        self.comboBox.setItemText(2, _translate("window2", "Selection Sort"))
        self.comboBox.setItemText(3, _translate("window2", "Count Sort"))
        self.comboBox.setItemText(4, _translate("window2", "Radix Sort"))
        self.comboBox.setItemText(5, _translate("window2", "Bucket Sort"))
        self.comboBox.setItemText(6, _translate("window2", "Quick Sort"))
        self.label_2.setText(_translate("window2", "Sort by"))
        self.radioButton.setText(_translate("window2", "Asending Order"))
        self.radioButton_2.setText(_translate("window2", "Decending Order"))
        self.pushButton_7.setText(_translate("window2", "Sort"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("window2", "University"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("window2", "Course Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("window2", "Lecture Videos"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("window2", "Duration"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("window2", "Students Enrolled"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("window2", "Professor"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("window2", "Price"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("window2", "Sorting"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("window2", "University"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("window2", "Course Name"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("window2", "Lecture Videos"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("window2", "Duration"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("window2", "Students Enrolled"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("window2", "Professor"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("window2", "Price"))
        self.label_3.setText(_translate("window2", "Search"))
        self.comboBox_2.setItemText(0, _translate("window2", "Search by integers"))
        self.comboBox_2.setItemText(1, _translate("window2", "Search by alphabets"))
        self.comboBox_2.setItemText(2, _translate("window2", "Search by a"))
        self.pushButton_8.setText(_translate("window2", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("window2", "Searching"))
        self.pushButton.setText(_translate("window2", "Home"))
        self.pushButton_2.setText(_translate("window2", "About"))
        self.pushButton_4.clicked.connect(self.loaddata1)
        self.loadData22()
        self.pushButton_7.clicked.connect(self.SelectionSort)
        self.pushButton_8.clicked.connect(self.getTextBySearch)
    def getTextBySearch(self):
        searchedText = self.lineEdit.text()
        with open ('C://Users/DEll/Documents/DSA tasks/DSA project/CS261F21PID11/scrapping/course.csv' , 'r') as file:
            data =  csv.reader(file)
            course = []
            for row in data:
                course.append(row)
        flag = False
        for k in range (0,7):
            for i in range (2,len(course)):
                if course[i][k] == searchedText:
                    flag = True
                    column = k
                    rowss = i 
                    break
            if flag == True:
                break
        
        self.tableWidget_3.setRowCount(1)
        row =0
        try:    
            val1 = str(course[rowss][0])
            val2 = str(course[rowss][1])
            val3 = str(course[rowss][2])
            val4 = str(course[rowss][3])
            val5 = str(course[rowss][4])
            val6 = str(course[rowss][5])
            val7 = str(course[rowss][6])
        except:
            val1 = "not found"
            val2 = "not found"
            val3 = "not found"
            val4 = "not found"
            val5 = "not found"
            val6 = "not found"
            val7 = "not found"
        self.tableWidget_3.setItem(row ,0, QtWidgets.QTableWidgetItem(val1))
        self.tableWidget_3.setItem(row, 1, QtWidgets.QTableWidgetItem(val2))
        self.tableWidget_3.setItem(row, 2, QtWidgets.QTableWidgetItem(val3))
        self.tableWidget_3.setItem(row, 3, QtWidgets.QTableWidgetItem(val4))
        self.tableWidget_3.setItem(row, 4, QtWidgets.QTableWidgetItem(val5))
        self.tableWidget_3.setItem(row, 5, QtWidgets.QTableWidgetItem(val6))
        self.tableWidget_3.setItem(row, 6, QtWidgets.QTableWidgetItem(val7))
        
        
        
    def loaddata1(self):
        for m in range(0,100):
            self.progressBar.setValue(m)
        with open ('C://Users/DEll/Documents/DSA tasks/DSA project/CS261F21PID11/scrapping/course.csv' , 'r') as file:
            data =  csv.reader(file)
            course = []
            for row in data:
                course.append(row)
            self.tableWidget.setRowCount(len(course))
            row =0
            for j in range(2,len(course)):
                try:
                   val1 = str(course[j][0])
                   val2 = str(course[j][1])
                   val3 = str(course[j][2])
                   val4 = str(course[j][3])
                   val5 = str(course[j][4])
                   val6 = str(course[j][5])
                   val7 = str(course[j][6])
                except:
                    pass
               
                self.tableWidget.setItem(row ,0, QtWidgets.QTableWidgetItem(val1))
                self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(val2))
                self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(val3))
                self.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(val4))
                self.tableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(val5))
                self.tableWidget.setItem(row, 5, QtWidgets.QTableWidgetItem(val6))
                self.tableWidget.setItem(row, 6, QtWidgets.QTableWidgetItem(val7))
                row = row +1
        
    def loadData22(self):
         with open ('C://Users/DEll/Documents/DSA tasks/DSA project/CS261F21PID11/scrapping/course.csv' , 'r') as file:
             data =  csv.reader(file)
             course = []
             for row in data:
                 course.append(row)
             self.tableWidget_2.setRowCount(len(course))
             row =0
             for j in range(2,len(course)):
                 try:
                    val1 = str(course[j][0])
                    val2 = str(course[j][1])
                    val3 = str(course[j][2])
                    val4 = str(course[j][3])
                    val5 = str(course[j][4])
                    val6 = str(course[j][5])
                    val7 = str(course[j][6])
                 except:
                     pass
                 
                 self.tableWidget_2.setItem(row ,0, QtWidgets.QTableWidgetItem(val1))
                 self.tableWidget_2.setItem(row, 1, QtWidgets.QTableWidgetItem(val2))
                 self.tableWidget_2.setItem(row, 2, QtWidgets.QTableWidgetItem(val3))
                 self.tableWidget_2.setItem(row, 3, QtWidgets.QTableWidgetItem(val4))
                 self.tableWidget_2.setItem(row, 4, QtWidgets.QTableWidgetItem(val5))
                 self.tableWidget_2.setItem(row, 5, QtWidgets.QTableWidgetItem(val6))
                 self.tableWidget_2.setItem(row, 6, QtWidgets.QTableWidgetItem(val7))
                 row = row +1
    def SelectionSort(self):
        with open ('C://Users/DEll/Documents/DSA tasks/DSA project/CS261F21PID11/scrapping/course.csv' , 'r') as file:
            data =  csv.reader(file)
            course = []
            for row in data:
                course.append(row)
        for k in range (0,7):
            for i in range (2,len(course)):
                minimum = i
                for j in range(i+1,len(course)):
                    if course[minimum][k] > course[j][k]:
                        minimum = j
                temp = course[i][k]
                course[i][k] = course[minimum][k]
                course[minimum][k] = temp
        self.tableWidget_2.setRowCount(len(course))
        row =0
        for j in range(2,len(course)):
            try:
               val1 = str(course[j][0])
               val2 = str(course[j][1])
               val3 = str(course[j][2])
               val4 = str(course[j][3])
               val5 = str(course[j][4])
               val6 = str(course[j][5])
               val7 = str(course[j][6])
            except:
                pass
            
            self.tableWidget_2.setItem(row ,0, QtWidgets.QTableWidgetItem(val1))
            self.tableWidget_2.setItem(row, 1, QtWidgets.QTableWidgetItem(val2))
            self.tableWidget_2.setItem(row, 2, QtWidgets.QTableWidgetItem(val3))
            self.tableWidget_2.setItem(row, 3, QtWidgets.QTableWidgetItem(val4))
            self.tableWidget_2.setItem(row, 4, QtWidgets.QTableWidgetItem(val5))
            self.tableWidget_2.setItem(row, 5, QtWidgets.QTableWidgetItem(val6))
            self.tableWidget_2.setItem(row, 6, QtWidgets.QTableWidgetItem(val7))
            row = row +1
            
                
        
import image


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window2 = QtWidgets.QMainWindow()
    ui = Ui_window2()
    ui.setupUi(window2)
    window2.show()
    sys.exit(app.exec_())
