# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from scrapping import *
from about import *

class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(786, 542)
        Home.setStyleSheet("background-color: rgb(43, 255, 231);\n"
"background-color: rgb(255, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(6, 2, 121, 511))
        self.label.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"background-color: rgb(85, 0, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Home_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Home_2.setGeometry(QtCore.QRect(10, 40, 111, 51))
        self.Home_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Home_2.setIconSize(QtCore.QSize(16, 16))
        self.Home_2.setObjectName("Home_2")
        self.Scrapping = QtWidgets.QPushButton(self.centralwidget)
        self.Scrapping.setGeometry(QtCore.QRect(10, 100, 111, 51))
        self.Scrapping.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Scrapping.setObjectName("Scrapping")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 10, 511, 41))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"background-color: rgb(85, 0, 255);\n"
"background-color: rgb(85, 0, 255);\n"
"background-color: rgb(0, 170, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"font: 75 26pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 90, 341, 211))
        self.label_3.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"background-image: url(:/newPrefix/pic/1.gif);\n"
"background-image: url(:/newPrefix/pic/1.gif);\n"
"background-image: url(:/newPrefix/1.gif);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/pic/1.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 340, 421, 21))
        self.label_4.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"background-color: rgb(85, 170, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 360, 421, 21))
        self.label_5.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(370, 430, 71, 41))
        self.label_6.setStyleSheet("background-image: url(:/newPrefix/OneDrive/Pictures/Screenshots/2021-10-26 (2).png);\n"
"background-image: url(:/newPrefix/pic/2021-10-26 (2).png);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/newPrefix/pic/2021-10-26 (2).png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(360, 470, 91, 20))
        self.label_8.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(510, 430, 61, 41))
        self.label_9.setStyleSheet("background-image: url(:/newPrefix/OneDrive/Pictures/Screenshots/2021-10-26 (3).png);\n"
"background-image: url(:/newPrefix/pic/2021-10-26 (3).png);")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/newPrefix/pic/2021-10-26 (3).png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(500, 470, 91, 20))
        self.label_10.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(410, 313, 51, 20))
        self.label_11.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.About = QtWidgets.QPushButton(self.centralwidget)
        self.About.setGeometry(QtCore.QRect(10, 160, 111, 51))
        self.About.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.About.setObjectName("About")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(250, 430, 71, 41))
        self.label_13.setStyleSheet("background-image: url(:/newPrefix/2.jpg);\n"
"background-image: url(:/newPrefix/pic/2.jpg);")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/newPrefix/pic/2.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(250, 470, 71, 16))
        self.label_14.setObjectName("label_14")
        Home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 21))
        self.menubar.setObjectName("menubar")
        Home.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Home)
        self.statusbar.setObjectName("statusbar")
        Home.setStatusBar(self.statusbar)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "MainWindow"))
        self.Home_2.setText(_translate("Home", "Home"))
        self.Scrapping.setText(_translate("Home", "Scrapping"))
        self.label_2.setText(_translate("Home", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:26pt; font-weight:72; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">     Online Course Scrapping </span></p></body></html>"))
        self.label_4.setText(_translate("Home", "Here we will Scrape the data of online courses  "))
        self.label_5.setText(_translate("Home", "We will share the courses of best universities from all around the world "))
        self.label_8.setText(_translate("Home", "Salahuddin6935"))
        self.label_10.setText(_translate("Home", "0312 6935581"))
        self.label_11.setText(_translate("Home", "about us"))
        self.About.setText(_translate("Home", "About"))
        self.label_14.setText(_translate("Home", "Contact us ->"))
        self.Scrapping.clicked.connect(self.openWindow)
        self.Scrapping.clicked.connect(Home.close)
        self.About.clicked.connect(self.windo2)
        self.About.clicked.connect(Home.close)
    def windo2(self):
        self.window3 = QtWidgets.QMainWindow()
        self.ui = Ui_window3()
        self.ui.setupUi(self.window3)
        self.window3.show()
    def openWindow(self):
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_window2()
        self.ui.setupUi(self.window2)
        self.window2.show()
        
import image


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())
